#!/bin/bash

# Exit immediately if a command exits with a non-zero status
set -e

# Get version from argument, default to 1.0.0 if not provided
VERSION=${1:-1.0.0}

echo "Starting build process for version $VERSION..."

# 1. Run npm run build
echo "Running npm run build..."
npm run build

# 1b. Remove source maps
echo "Removing source maps..."
find build -name "*.map" -type f -delete

# 2. Run npm run build:legacy
# echo "Running npm run build:legacy..."
# npm run build:legacy

# 3. Rename license files
# echo "Renaming license files..."
# if [ -f "build/admin-legacy.js.LICENSE.txt" ]; then
#     mv build/admin-legacy.js.LICENSE.txt build/admin.js.LICENSE.txt
#     echo "Renamed build/admin-legacy.js.LICENSE.txt to build/admin.js.LICENSE.txt"
# fi

# if [ -f "build/settings-legacy.js.LICENSE.txt" ]; then
#     mv build/settings-legacy.js.LICENSE.txt build/settings.js.LICENSE.txt
#     echo "Renamed build/settings-legacy.js.LICENSE.txt to build/settings.js.LICENSE.txt"
# fi

# 4. Add headers
# List of files to edit
FILES=("build/admin.js" "build/settings.js" )

# Loop through each file and prepend the header
for file in "${FILES[@]}"; do
    if [ -f "$file" ]; then
        echo "Adding header to $file..."
        
        # Determine which license file to refer to
        LICENSE_FILE="admin.js.LICENSE.txt"
        if [[ "$file" == *"settings"* ]]; then
            LICENSE_FILE="settings.js.LICENSE.txt"
        fi

        HEADER="/*
 * NotifyBay
 * Copyright (c) $(date +%Y) WPAnchorBay - https://wpanchorbay.com
 *
 * This software is licensed under the GPLv2 or later.
 * This file is generated from un-compiled source code. Do not edit this file directly.
 *
 * Source Code (Root): https://github.com/wpanchorbay/notifybay-free/tree/$VERSION/
 * Source Code (Admin): https://github.com/wpanchorbay/notifybay-free/tree/$VERSION/src
 *
 * For license information please see $LICENSE_FILE
 */"

        echo "$HEADER" | cat - "$file" > "${file}.tmp" && mv "${file}.tmp" "$file"
        echo "Successfully added header to $file"
    else
        echo "Warning: File $file not found."
    fi
done

echo "Build and header addition complete for version $VERSION."
