<?php
/**
 * Worker Engine.
 *
 * Processes individual email jobs generated by the Dispatcher.
 *
 * @package    NotifyBay
 * @subpackage Engine
 * @since      1.0.0
 * @author     WPAnchorBay <sankarsan@wpanchorbay.com>
 */

namespace NotifyBay\Engine;

use NotifyBay\Core\Plugin;
use NotifyBay\Helper\TemplateRenderer;
use NotifyBay\Models\Lead;
use NotifyBay\Core\Settings;

// Exit if accessed directly.
if ( ! defined( 'ABSPATH' ) ) {
	exit;
}

/**
 * Class Worker
 */
class Worker {

	/**
	 * The single instance of the class.
	 *
	 * @var Worker
	 */
	private static $instance = null;

	/**
	 * Get the instance.
	 *
	 * @return Worker
	 */
	public static function get_instance() {
		if ( null === self::$instance ) {
			self::$instance = new self();
		}
		return self::$instance;
	}

	/**
	 * Register hooks.
	 *
	 * @param Plugin $plugin The plugin instance.
	 */
	public function run( Plugin $plugin ) {
		$loader = $plugin->get_loader();
		$loader->add_action( 'notifybay_send_email_worker', $this, 'process_job', 10, 2 );
	}

	/**
	 * Get the registered email-event definitions.
	 *
	 * Each event is keyed by its event type string (e.g. `waitlist_restock`) and maps
	 * to how to build its subject/body and what lead status to transition to after a
	 * successful send. NotifyBay Pro registers premium events (e.g. `wishlist_price_drop`,
	 * `hurry_low_stock`) here rather than the Worker special-casing them, so this is the
	 * single place event-type-specific behavior is defined.
	 *
	 * @since 1.0.0
	 * @hook notifybay_email_events
	 * @return array Map of event_type => array{
	 *     subject_setting?: string,   Settings key holding a custom subject (optional).
	 *     subject_default: string,    Fallback subject with placeholders.
	 *     body_setting?: string,      Settings key holding a custom body (optional).
	 *     template: string,           TemplateRenderer template path.
	 *     status_after: string|null,  Lead status to set after a successful send, or null to leave unchanged.
	 *     is_verification?: bool,     True bypasses the `processing`-status precondition (double opt-in flow).
	 * }.
	 */
	public function get_event_registry() {
		return apply_filters(
			'notifybay_email_events',
			array(
				'waitlist_restock' => array(
					'wc_email'        => 'notifybay_restock',
					'subject_setting' => 'email_restockSubject',
					'subject_default' => __( 'Good news! {product_name} is back in stock', 'notifybay-waitlist-and-stock-alert-woo' ),
					'body_setting'    => 'email_restockBody',
					'template'        => 'emails/restock-notification',
					'status_after'    => 'notified',
				),
				'verification'     => array(
					'wc_email'        => 'notifybay_verification',
					'subject_setting' => 'email_verificationSubject',
					'subject_default' => __( 'Verify your subscription to {product_name}', 'notifybay-waitlist-and-stock-alert-woo' ),
					'body_setting'    => 'email_verificationBody',
					'template'        => 'emails/verification',
					'status_after'    => null,
					'is_verification' => true,
				),
			)
		);
	}

	/**
	 * Process a single email job.
	 *
	 * @param int    $lead_id    The ID of the lead.
	 * @param string $event_type The type of event (e.g., 'waitlist_restock').
	 */
	public function process_job( $lead_id, $event_type ) {

		$lead = Lead::find( $lead_id );
		if ( ! $lead ) {

			return;
		}

		$events = $this->get_event_registry();

		if ( ! isset( $events[ $event_type ] ) ) {

			// Unknown event type: don't send anything, and don't touch the lead's
			// status. This happens when a premium event (e.g. wishlist_price_drop)
			// was enqueued while NotifyBay Pro was active but is now processed with
			// Pro deactivated/missing (e.g. right after a Free plugin update, before
			// Pro catches up). Sending would mean guessing at content for an event we
			// don't understand — instead leave the lead in `processing`; the stale-lead
			// reaper (CronTasks::recover_stale_processing_leads) resets it back to
			// `active` after 15 minutes so it is retried once Pro is active again.
			return;
		}

		$config = $events[ $event_type ];

		if ( empty( $config['is_verification'] ) && 'processing' !== $lead->status ) {

			return; // For non-verification emails, lead must be in processing status
		}

		// WPML/Polylang compatibility: Switch to user's locale
		$original_locale = determine_locale();
		$user_locale     = $lead->user_locale;
		$switched_locale = false;

		if ( $user_locale && $user_locale !== $original_locale && function_exists( 'switch_to_locale' ) ) {
			switch_to_locale( $user_locale );
			$switched_locale = true;
		}

		// Prepare email data
		$product      = wc_get_product( $lead->variation_id ? $lead->variation_id : $lead->product_id );
		$product_name = $lead->product_name_snapshot ? $lead->product_name_snapshot : ( $product ? $product->get_name() : __( 'Product', 'notifybay-waitlist-and-stock-alert-woo' ) );
		$stock_qty    = $product ? $product->get_stock_quantity() : 0;

		// Customer Personalization
		$customer_name       = __( 'Customer', 'notifybay-waitlist-and-stock-alert-woo' );
		$customer_first_name = __( 'Customer', 'notifybay-waitlist-and-stock-alert-woo' );

		if ( $lead->user_id > 0 ) {
			$user = get_userdata( $lead->user_id );
			if ( $user ) {
				$customer_name       = $user->display_name;
				$customer_first_name = $user->first_name ? $user->first_name : $user->display_name;
			}
		}

		$placeholders = array(
			'{product_name}'          => $product_name,
			'{customer_name}'         => $customer_name,
			'{customer_first_name}'   => $customer_first_name,
			'{stock_qty}'             => $stock_qty,
			'{original_product_name}' => $lead->product_name_snapshot ? $lead->product_name_snapshot : $product_name,
		);

		$to = $lead->user_email;

		// Build the per-lead render context shared by the WooCommerce-email path.
		$is_verification = ! empty( $config['is_verification'] );

		$context = array(
			'product_name'          => $product_name,
			'customer_name'         => $customer_name,
			'customer_first_name'   => $customer_first_name,
			'stock_qty'             => $stock_qty,
			'original_product_name' => $lead->product_name_snapshot ? $lead->product_name_snapshot : $product_name,
		);

		if ( $is_verification ) {
			$context['verify_url'] = site_url( '/?notifybay_action=verify&token=' . $lead->verification_token );
		} else {
			$buy_link = $product ? $product->get_permalink() : site_url();
			$buy_link = add_query_arg(
				array(
					'utm_source'   => 'notifybay',
					'utm_medium'   => 'email',
					'utm_campaign' => $event_type,
				),
				$buy_link
			);

			$context['buy_link']        = $buy_link;
			$context['unsubscribe_url'] = site_url( '/?notifybay_action=unsubscribe&token=' . $lead->verification_token );
		}

		// Prefer the native WooCommerce email for this event when one is
		// registered (all first-party events use one). The Worker still owns
		// sending; the WC_Email only renders (store branding, theme-overridable
		// template) and supplies the merchant-configured subject/heading.
		$wc_email = ! empty( $config['wc_email'] ) ? \NotifyBay\Emails\EmailManager::get_email( $config['wc_email'] ) : null;

		if ( $wc_email ) {
			// Engine settings already gated dispatch; the WooCommerce "Enable
			// this email" toggle is the final say. If disabled, consume the lead
			// (so it does not loop through the stale-lead reaper) without sending.
			if ( ! $wc_email->is_enabled() ) {
				if ( ! empty( $config['status_after'] ) ) {
					$lead->status      = $config['status_after'];
					$lead->notified_at = current_time( 'mysql' );
					$lead->updated_at  = current_time( 'mysql' );
					$lead->save();
				}
				if ( $switched_locale && function_exists( 'restore_current_locale' ) ) {
					restore_current_locale();
				}
				return;
			}

			$wc_email->set_context( $lead, $context );
			$subject = $wc_email->get_subject();
			$message = $wc_email->render_final_html();
		} else {
			// Legacy fallback (pre-WC_Email path): render via TemplateRenderer.
			$subject = $this->get_subject( $config, $placeholders );
			$message = $this->get_message( $lead, $event_type, $config, $placeholders );
		}

		$settings = Settings::get_instance();

		$from_name  = $settings->get_settings( 'email_fromName' );
		$from_email = $settings->get_settings( 'email_fromEmail' );

		// Fallback to avoid 'wordpress@localhost' validation errors in local environments
		if ( empty( $from_name ) ) {
			$from_name = get_bloginfo( 'name' );
		}
		if ( empty( $from_email ) ) {
			$from_email = get_option( 'admin_email' );
		}

		$headers = array(
			'Content-Type: text/html; charset=UTF-8',
			'List-Unsubscribe: <' . site_url( '/?notifybay_action=unsubscribe&token=' . $lead->verification_token ) . '>',
		);

		if ( ! empty( $from_name ) && ! empty( $from_email ) ) {
			$headers[] = 'From: ' . $from_name . ' <' . $from_email . '>';
		}

		// Send email
		$sent = wp_mail( $to, $subject, $message, $headers );

		// Restore locale
		if ( $switched_locale && function_exists( 'restore_current_locale' ) ) {
			restore_current_locale();
		}

		if ( $sent ) {

			if ( ! empty( $config['status_after'] ) ) {

				$lead->status      = $config['status_after'];
				$lead->notified_at = current_time( 'mysql' );
				$lead->updated_at  = current_time( 'mysql' );
				$lead->save();
			}
		} else {

			$this->handle_failure( $lead, $event_type );
		}
	}

	/**
	 * Handle email failure with exponential backoff.
	 *
	 * @param Lead   $lead       The lead model.
	 * @param string $event_type The event type.
	 */
	private function handle_failure( Lead $lead, $event_type ) {
		$lead->retry_count = (int) $lead->retry_count + 1;
		$lead->updated_at  = current_time( 'mysql' );

		if ( $lead->retry_count >= 3 ) {
			$lead->status = 'failed';
			$lead->save();
			return;
		}

		$lead->status = 'processing';
		$lead->save();

		// Exponential backoff: 5 min, 30 min, 2 hours (120 min)
		$delays = array(
			1 => 300,
			2 => 1800,
			3 => 7200,
		);
		$delay  = isset( $delays[ $lead->retry_count ] ) ? $delays[ $lead->retry_count ] : 300;

		if ( function_exists( 'as_schedule_single_action' ) ) {
			as_schedule_single_action( time() + $delay, 'notifybay_send_email_worker', array( $lead->id, $event_type ), 'notifybay_alerts' );
		}
	}

	/**
	 * Get the email subject for an event, from its registry config.
	 *
	 * @param array $config       The event's registry config (see get_event_registry()).
	 * @param array $placeholders Dynamic placeholders.
	 * @return string
	 */
	private function get_subject( array $config, $placeholders ) {
		$settings = Settings::get_instance();

		$custom_subject = ! empty( $config['subject_setting'] ) ? $settings->get_settings( $config['subject_setting'] ) : '';
		$subject        = ! empty( $custom_subject ) ? $custom_subject : $config['subject_default'];

		return strtr( $subject, $placeholders );
	}

	/**
	 * Get the email message body for an event, from its registry config.
	 *
	 * @param Lead   $lead         The lead model.
	 * @param string $event_type   Event type.
	 * @param array  $config       The event's registry config (see get_event_registry()).
	 * @param array  $placeholders Dynamic placeholders.
	 * @return string
	 */
	private function get_message( Lead $lead, $event_type, array $config, $placeholders ) {
		$settings = Settings::get_instance();

		if ( ! empty( $config['is_verification'] ) ) {
			$verify_url = site_url( '/?notifybay_action=verify&token=' . $lead->verification_token );

			$custom_body = ! empty( $config['body_setting'] ) ? $settings->get_settings( $config['body_setting'] ) : '';
			if ( ! empty( $custom_body ) ) {
				$placeholders['{verify_url}'] = $verify_url;
				return wpautop( strtr( $custom_body, $placeholders ) );
			}

			return TemplateRenderer::render(
				$config['template'],
				array(
					'verify_url'   => $verify_url,
					'product_name' => $placeholders['{product_name}'],
				),
				true
			);
		}

		$product  = wc_get_product( $lead->variation_id ? $lead->variation_id : $lead->product_id );
		$buy_link = $product ? $product->get_permalink() : site_url();

		// Add UTM parameters (Automated UTM Attribution)
		$buy_link = add_query_arg(
			array(
				'utm_source'   => 'notifybay',
				'utm_medium'   => 'email',
				'utm_campaign' => $event_type,
			),
			$buy_link
		);

		$unsubscribe_url = site_url( '/?notifybay_action=unsubscribe&token=' . $lead->verification_token );

		// Check for custom body from settings
		$custom_body = ! empty( $config['body_setting'] ) ? $settings->get_settings( $config['body_setting'] ) : '';

		if ( ! empty( $custom_body ) ) {
			$placeholders['{buy_link}']         = $buy_link;
			$placeholders['{unsubscribe_link}'] = $unsubscribe_url;
			return wpautop( strtr( $custom_body, $placeholders ) );
		}

		return TemplateRenderer::render(
			$config['template'],
			array(
				'lead'                => $lead,
				'product_name'        => $placeholders['{product_name}'],
				'customer_name'       => $placeholders['{customer_name}'],
				'customer_first_name' => $placeholders['{customer_first_name}'],
				'buy_link'            => $buy_link,
				'unsubscribe_url'     => $unsubscribe_url,
				'stock_qty'           => $placeholders['{stock_qty}'],
			),
			true
		);
	}
}
